"""PDF generation service for storybooks."""
import os
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from app.config import Config
from app.utils.logging_config import get_logger

logger = get_logger('pdf_service')


class PDFService:
    """Service for generating PDF storybooks."""
    
    def __init__(self):
        """Initialize PDF service."""
        self.upload_folder = Config.UPLOAD_FOLDER
        os.makedirs(self.upload_folder, exist_ok=True)
    
    def create_storybook_pdf(self, story_data, image_paths, story_id):
        """Create a premium children's book PDF.
        
        Args:
            story_data: Story data dictionary
            image_paths: List of paths to page images
            story_id: Unique story identifier
        
        Returns:
            str: Path to generated PDF file
        """
        logger.info(f"Creating PDF for story {story_id}", extra={
            'story_id': story_id,
            'num_pages': len(story_data.get('pages', []))
        })
        
        filename = f"storybook_{story_id}.pdf"
        filepath = os.path.join(self.upload_folder, filename)
        
        # Create document
        doc = SimpleDocTemplate(
            filepath,
            pagesize=A4,
            topMargin=0.5*inch,
            bottomMargin=0.5*inch
        )
        
        # Custom border drawing function
        def draw_page_border(canvas, doc):
            canvas.saveState()
            canvas.setStrokeColor(colors.gold)
            canvas.setLineWidth(4)
            canvas.rect(0.3*inch, 0.3*inch, A4[0]-0.6*inch, A4[1]-0.6*inch)
            canvas.restoreState()
        
        # Setup styles
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'MainTitle',
            parent=styles['Heading1'],
            fontSize=32,
            alignment=1,
            textColor=colors.darkblue,
            spaceAfter=20,
            fontName='Helvetica-Bold'
        )
        
        body_style = ParagraphStyle(
            'StoryBody',
            parent=styles['Normal'],
            fontSize=18,
            alignment=1,
            leading=24,
            spaceBefore=20,
            fontName='Helvetica'
        )
        
        page_num_style = ParagraphStyle(
            'PageNum',
            parent=styles['Normal'],
            fontSize=12,
            alignment=1,
            textColor=colors.gray
        )
        
        story = []
        
        # Cover page
        story.append(Spacer(1, 2*inch))
        story.append(Paragraph(story_data.get('title', 'Untitled Story'), title_style))
        story.append(Spacer(1, 0.5*inch))
        story.append(Paragraph("A Story Generated by AI", styles['Heading3']))
        story.append(Spacer(1, 2*inch))
        story.append(Paragraph("🤖 ✨", title_style))
        story.append(PageBreak())
        
        # Story pages
        for i, page in enumerate(story_data.get('pages', [])):
            page_num = page.get('page', i+1)
            
            # Add image if exists
            if i < len(image_paths) and image_paths[i] and os.path.exists(image_paths[i]):
                try:
                    img = RLImage(image_paths[i], width=6*inch, height=4.5*inch)
                    story.append(img)
                except Exception as e:
                    logger.warning(f"Failed to add image to PDF: {e}")
            
            story.append(Spacer(1, 20))
            story.append(Paragraph(page.get('text', ''), body_style))
            story.append(Spacer(1, 30))
            story.append(Paragraph(f"- {page_num} -", page_num_style))
            story.append(PageBreak())
        
        # Back cover with moral
        if 'moral' in story_data:
            story.append(Spacer(1, 3*inch))
            story.append(Paragraph("The End", title_style))
            story.append(Spacer(1, 30))
            story.append(Paragraph(
                f"<b>Moral of the Story:</b><br/>{story_data['moral']}",
                body_style
            ))
        
        # Build PDF with borders
        doc.build(story, onFirstPage=draw_page_border, onLaterPages=draw_page_border)
        logger.info(f"PDF created successfully: {filepath}")
        
        return filepath


# Singleton instance
_pdf_service = None


def get_pdf_service():
    """Get or create PDF service singleton.
    
    Returns:
        PDFService instance
    """
    global _pdf_service
    if _pdf_service is None:
        _pdf_service = PDFService()
    return _pdf_service
